name: Concurrency Test

on:
  pull_request:
    types: [opened]
    
concurrency:
  group: ${{github.workflow_ref}}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump GitHub workflow ref
      run: echo ${{github.workflow_ref}}

