name: Concurrency Test

on:
  pull_request:
    types: [opened,closed]
  issue_comment:
    types: [created,edited,deleted]
  workflow_dispatch:
    
concurrency:
  group: ${{github.event.comment.body}}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump GitHub comment
      run: echo ${{github.event.comment.body}}
      
