name: Concurrency Test

on:
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.workflow_ref }}
