name: Concurrency Test

on:
  workflow_dispatch:
    
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
