name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}-${{ github.workflow }}
